version: '2'


services:
    db:
        image: mongo:latest
        container_name: db
        environment:
            MONGO_INITDB_DATABASE: Database
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27107:27017
        command: mongod

    web:
        build:
            context: ./RoundRobin
            dockerfile: Dockerfile
        depends_on:
            - Log
        container_name: web
        ports:
            - "8000:6000"

    Log:
        build:
            context: ./ServicesLog
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8001-8003:6000"

volumes:
    mongodb:
    mongodb_config:
