version: '2'


services:
    db:
        image: mongo:latest
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
    robin:
        build:
            context: ./RoundRobin
            dockerfile: Dockerfile
        container_name: robin
        ports:
            - "8000:6000"

    web1:
        build:
            context: ./ServicesLog
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8001-8003:7000"

volumes:
    mongodb:
    mongodb_config:
